- host: ""
  device_type: "cisco_xr"
  username: "clab"
  password: "clab@123"
- host: ""
  device_type: "cisco_xr"
  username: "clab"
  password: "clab@123"
- host: ""
  device_type: "juniper_junos"
  username: "clab"
  password: "clab123"
