- host: "172.16.4.2"
  device_type: "cisco_xr"
  username: "clab"
  password: "clab@123"
- host: "172.16.4.3"
  device_type: "cisco_xr"
  username: "clab"
  password: "clab@123"
- host: "172.16.4.4"
  device_type: "juniper_junos"
  username: "clab"
  password: "clab123"