---
- name: Move VLANs between Cisco_1 and Juniper
  hosts: all
  gather_facts: no

  vars:
    cisco_1_interface_old: "Gi0/0/0/1"
    juniper_interface: "eth1"
    cisco_1_interface_new: "Gi0/0/0/0"
    cisco_2_interface_new: "Gi0/0/0/0"
    vlan_numbers: "{{ [] }}"
    vlan_file: vlans_juniper.txt
      #vlan_numbers: []

  collections:
    - cisco.iosxr
    - junipernetworks.junos
    - juniper.device

  roles:
    - Juniper.junos

  tasks:
    - name: Get VLANs on Juniper eth1 interface
      connection: local
      juniper_junos_command:
        commands: "show configuration interfaces {{ juniper_interface }}"
      register: juniper_interface_info
      when: "'juniper' in inventory_hostname"

    
    - name: Extract VLAN numbers from interface
      connection: local
      set_fact:
        vlan_numbers: "{{ vlan_numbers | default([]) + [item.split()[1]] }}"
      loop: "{{ juniper_interface_info.stdout_lines | select('match', '^    vlan-id ') | map('regex_replace',';','') | list }}"
      when: "'juniper' in inventory_hostname"

    - name: Configure VLANS for new interface on Cisco_2
      cisco.iosxr.iosxr_l2_interfaces:
        config:
          - name: "{{ cisco_2_interface_new }}.{{ item }}"
            encapsulation: 
             dot1q: "{{ item }}"
        state: merged
      with_items: "{{ hostvars['juniper']['vlan_numbers'] }}"
      when: "'cisco_2' in inventory_hostname"
  
    - name: Configure VLANs for the new interface on Cisco_1
      cisco.iosxr.iosxr_l2_interfaces:
        config:
          - name: "{{ cisco_1_interface_new }}.{{ item }}"
            encapsulation: 
             dot1q: "{{ item }}"
        state: merged
      with_items: "{{ hostvars['juniper']['vlan_numbers'] }}"
      when: "'cisco_1' in inventory_hostname"

    
    - name: Enable new interface on Cisco_2
      cisco.iosxr.iosxr_interfaces:
        config:
          - name: "{{ cisco_2_interface_new }}"
            description: New_path
            enabled: true 
        state: merged
      with_items: "{{ hostvars['juniper']['vlan_numbers'] }}"
      when: "'cisco_2' in inventory_hostname"

    - name: Disable old interface and enable new interface in Cisco_1
      cisco.iosxr.iosxr_interfaces:
        config:
          - name: "{{ cisco_1_interface_old }}"
            enabled: false 
          - name: "{{ cisco_1_interface_new }}"
            description: New_path
            enabled: true
        state: merged
      when: "'cisco_1' in inventory_hostname"
