---
all:
  children:
    cisco:
      hosts:
        cisco_1:
          ansible_host: 172.16.1.2
          device_type: "IOSXR"
        cisco_2:
          ansible_host: 172.16.1.3
          device_type: "IOSXR"
      vars:
        ansible_network_os: ios
        ansible_user: clab
        ansible_connection: ansible.netcommon.network_cli
        ansible_ssh_pass: clab@123
    junos:
      vars:
        ansible_user: clab
        ansible_ssh_pass: clab123
      hosts:
        juniper:
          ansible_host: 172.16.1.4
          device_type: "JUNOS"
