---
all:
  children:
    cisco:
      hosts:
        cisco_1:
          ansible_host: 172.16.20.2
          device_type: "IOSXR"
        cisco_2:
          ansible_host: 172.16.20.3
          device_type: "IOSXR"
      vars:
        ansible_user: clab
        ansible_ssh_pass: clab@123
    junos:
      vars:
        ansible_user: clab
        ansible_ssh_pass: clab123
      hosts:
        juniper:
          ansible_host: 172.16.20.4
          device_type: "JUNOS"
